---

any(
  include('matrix'),
  list(
    include('technique'),
  ),
  list(
    include('tactic'),
  ),
  list(
    include('case-study'),
  )
)

---

matrix:
  id: str()
  name: str()
  version: num()
  tactics: list(include('object-id'))
  data: list(include('data-source'))

data-source:
  uri: str()
  format: enum('ADVML', 'STIX')

object-id: regex('([a-zA-Z]+\.)*([A-Z]+[0-9]{4})')

object-type: enum('tactic', 'technique', 'case-study')

technique:
  id: include('object-id')
  object-type: include('object-type')
  name: str()
  description: str()
  tactics: list(include('object-id'), required=False)
  subtechnique-of: include('object-id', required=False)

tactic:
  id: include('object-id')
  object-type: include('object-type')
  name: str()
  description: str()

case-study:
  id: str()
  object-type: str()
  name: str()
  summary: str()
  incident-date: day()
  procedure: list(include('case-study-procedure'))
  reported-by: any(null(), str(), list(str()))
  references: any(null(), str(), list(str()))

case-study-procedure:
  tactic: include('object-id')
  technique: include('object-id')
  description: str()

reference:
  title: str()
  author: list(str())
  year: int()
  url: str()
