---

any(
  map(
    include('matrix')
  ),
  map(
    include('technique'),
    include('external-reference'),
    key=include('object-id')
  ),
  map(
    include('tactic'),
    include('external-reference'),
    key=include('object-id')
  ),
  map(
    include('case-study'),
    key=include('object-id')
  )
)

---

matrix:
  name: str()
  version: num()
  tactics: include('matrix-object')
  techniques: include('matrix-object')
  case-studies: include('matrix-object', required=False)
  external: map(include('matrix'), required=False)

matrix-object:
  prefix: str()
  format: enum('ADVML', 'STIX')
  data: str()

object-id: regex('([a-zA-Z]+\.)*([A-Z]+[0-9]{4})')

technique:
  name: str()
  description: str()
  tactics: list(include('object-id'))
  subtechnique-of: include('object-id', required=False)

tactic:
  name: str()
  description: str()

case-study:
  name: str()
  summary: str()
  incident_date: str()
  procedure: list(include('case-study-procedure'))
  reported_by: str()
  verified_by: str()
  sources: list(str())

case-study-procedure:
  tactic: include('object-id')
  technique: include('object-id')
  description: str()

external-reference: null()
