---

any(
  map(
    include('matrix')
  ),
  map(
    include('technique'),
    include('external-reference'),
    key=include('object-id')
  ),
  map(
    include('tactic'),
    include('external-reference'),
    key=include('object-id')
  ),
  )
)

---

matrix:
  name: str()
  version: num()
  tactics: include('matrix-object')
  techniques: include('matrix-object')
  external: map(include('matrix'), required=False)

matrix-object:
  prefix: str()
  format: enum('ADVML', 'STIX')
  data: str()

object-id: regex('([a-zA-Z]+\.)*([A-Z]+[0-9]{4})')

technique:
  name: str()
  description: str()
  tactics: list(include('object-id'))
  subtechnique-of: include('object-id', required=False)

tactic:
  name: str()
  description: str()

external-reference: null()
